
PROTO := $(wildcard *.proto) $(wildcard */*.proto)
CPP_HEADERS = $(PROTO:.proto=.pb.h)

%.pb.h %.pb.cc: %.proto
	protoc -I. -I.. --cpp_out=. $<
	protoc -I. -I.. --python_out=. $<

sources: $(CPP_HEADERS)
	@touch common/__init__.py
	@touch http/__init__.py
	@touch notification/__init__.py
